name: Greetings #

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello 👋 Thats a nice shoot"
        pr-message: "Yo, **#** Thank you for taking your time to contribute to this project  "
